<?php

namespace SilverStripe\Cow\Steps\Release;

use Exception;
use SilverStripe\Cow\Model\Changelog\Changelog;
use SilverStripe\Cow\Model\Changelog\ChangelogLibrary;
use SilverStripe\Cow\Model\Modules\Library;
use SilverStripe\Cow\Model\Release\ComposerConstraint;
use SilverStripe\Cow\Model\Release\LibraryRelease;
use SilverStripe\Cow\Model\Release\Version;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Creates a new changelog
 */
class CreateChangelog extends ReleaseStep
{
    /**
     * Below this line, any text will be automatically regenerated
     *
     * @var string
     */
    protected $autogeneratedDelimeter = "<!--- Changes below this line will be automatically regenerated -->";

    public function run(InputInterface $input, OutputInterface $output)
    {
        $this->log($output, "Generating changelog content for all releases in this plan");

        // Generate changelogs for each element in this plan
        $this->recursiveGenerateChangelog($output, $this->getReleasePlan());

        $this->log($output, "All changelog generation complete!");
    }

    /**
     * Generate changelogs for this release, and all child nodes
     *
     * @param OutputInterface $output
     * @param LibraryRelease $release
     */
    protected function recursiveGenerateChangelog(OutputInterface $output, LibraryRelease $release)
    {
        // Don't generate changelogs for non-release upgrades (e.g. bump to existing tag)
        if (!$release->getIsNewRelease()) {
            return;
        }

        // Generate changelog for this library only
        $this->generateChangelog($output, $release);

        // Recurse
        foreach ($release->getItems() as $child) {
            $this->recursiveGenerateChangelog($output, $child);
        }
    }

    /**
     * Generate changelog for this node only
     *
     * @param OutputInterface $output
     * @param LibraryRelease $release
     * @throws Exception
     */
    protected function generateChangelog(OutputInterface $output, LibraryRelease $release)
    {
        // Determine if this library has a changelog configured
        if (!$release->getLibrary()->hasChangelog()) {
            return;
        }

        // Get from version
        $fromVersion = $release->getPriorVersion();
        if (!$fromVersion) {
            $this->log(
                $output,
                "No prior version for library <info>" . $release->getLibrary()->getName() . '</info>, '
                . "skipping changelog for initial release"
            );
            return;
        }

        $this->log(
            $output,
            "Generating changelog for library <info>" . $release->getLibrary()->getName() . '</info>'
            . ' (<comment>' . $fromVersion->getValue() . '</comment> to '
            . '<info>' . $release->getVersion()->getValue() . '</info>)'
        );

        // Given a from version for this release, determine the "from" version for all child dependencies.
        // This does a deep search through composer dependencies and recursively checks out old versions
        // of composer.json to determine historic version information
        $changelogLibrary = $this->getChangelogLibrary($release, $fromVersion);

        // Preview diffs to generate for this changelog
        $count = $changelogLibrary->count();
        $this->log($output, "Found changes in <info>{$count}</info> modules:");
        foreach ($changelogLibrary->getAllItems(true) as $item) {
            $prior = $item->getPriorVersion()->getValue();
            $version = $item->getRelease()->getVersion()->getValue();
            $name = $item->getRelease()->getLibrary()->getName();
            $this->log($output, " * <info>{$name}</info> from <info>{$prior}</info> to <info>{$version}</info>");
        }

        // Generate markedown from plan
        $changelog = new Changelog($changelogLibrary);
        /** @var \SilverStripe\Cow\Commands\Release\Changelog $command */
        $command = $this->getCommand();
        $changelog->setIncludeOtherChanges($command->getIncludeOtherChanges());

        $content = $changelog->getMarkdown($output, $release->getLibrary()->getChangelogFormat());

        // Store this changelog
        $this->storeChangelog($output, $changelogLibrary, $content);
    }

    /**
     * @param OutputInterface $output
     * @param ChangelogLibrary $changelogLibrary Changelog details
     * @param string $content content to save
     */
    protected function storeChangelog(OutputInterface $output, ChangelogLibrary $changelogLibrary, $content)
    {
        // Determine saving mechanism
        $version = $changelogLibrary->getRelease()->getVersion();
        $library = $changelogLibrary->getRelease()->getLibrary();
        $changelogHolder = $library->getChangelogHolder();

        // Store in local path
        $path = $library->getChangelogPath($version);
        if ($path) {
            // Generate header
            $fullPath = $changelogHolder->getDirectory() . '/' . $path;
            $existingContent = file_exists($fullPath) ? file_get_contents($fullPath) : null;
            $header = $this->getFileHeader($output, $version, $existingContent);

            // Write and commit changes
            $this->log($output, "Writing changelog to <info>{$fullPath}</info>");
            $dirname = dirname($fullPath);
            if (!is_dir($dirname)) {
                mkdir($dirname, 0777, true);
            }
            file_put_contents($fullPath, $header . $content);
            $this->commitChanges($output, $changelogHolder, $version, $fullPath);
        }

        // Store in yml to later push to git
        if ($library->hasGithubChangelog()) {
            // Note that we skip file header for github changes (for simplicity)
            // Write and commit changes to .cow.plan.json
            $this->log($output, "Caching changelog to push to github");
            $changelogLibrary->getRelease()->setChangelog($content);
            $this->getProject()->saveCachedPlan($this->getReleasePlan());
        }
    }

    /**
     * Determine historic release plan from a past composer constraint
     *
     * @param LibraryRelease $newRelease
     * @param Version $historicVersion
     * @return ChangelogLibrary Changelog information for a library
     */
    protected function getChangelogLibrary(LibraryRelease $newRelease, Version $historicVersion)
    {
        // Build root release node
        $historicRelease = new ChangelogLibrary($newRelease, $historicVersion);

        // Check if "stable only" mode
        $preferStable = $newRelease->getVersion()->isStable();

        // Check all dependencies from this past commit.
        // Note that we flatten both current and historic dependecy trees in case dependencies
        // have been re-arranged since the prior tag.
        $pastComposer = null;
        foreach ($newRelease->getAllItems() as $childNewRelease) {
            /** LibraryRelease $childNewRelease */
            // Lazy-load historic composer content as needed
            if (!isset($pastComposer)) {
                // Get flat composer history up to 6 levels deep
                $pastComposer = $newRelease
                    ->getLibrary()
                    ->getHistoryComposerData($historicVersion->getValue(), true, 6, $preferStable);
            }

            // Check if this release has a historic tag.
            $childReleaseName = $childNewRelease->getLibrary()->getName();
            if (empty($pastComposer['require'][$childReleaseName])) {
                continue;
            }

            // Use an explicitly specified previous version
            $childHistoricVersion = $childNewRelease->getPriorVersion(false);
            if (!$childHistoricVersion) {
                $historicConstraintName = $pastComposer['require'][$childReleaseName];

                // Get oldest existing tag that matches the given constraint as the "from" for changelog purposes.
                $historicConstraint = new ComposerConstraint(
                    $historicConstraintName,
                    $historicVersion,
                    $childReleaseName
                );
                $childHistoricVersion = $childNewRelease->getLibrary()->getOldestVersionMatching(
                    $historicConstraint,
                    $childNewRelease->getVersion()->isStable()
                );
            }

            if (!$childHistoricVersion) {
                throw new \LogicException(
                    "No historic version for library {$childReleaseName} matches constraint {$historicConstraintName}"
                );
            }

            // Check if to == from version
            if ($childHistoricVersion->getValue() === $childNewRelease->getVersion()->getValue()) {
                continue;
            }

            // Add this module as a changelog
            $childChangelog = new ChangelogLibrary($childNewRelease, $childHistoricVersion);
            $historicRelease->addItem($childChangelog);
        }

        return $historicRelease;
    }


    /**
     * Get header component to put before the changelog content
     *
     * @param OutputInterface $output
     * @param Version $version
     * @param string $content Existing changelog markdown
     * @return string
     */
    protected function getFileHeader(OutputInterface $output, Version $version, $content)
    {
        // Generate new header if no file exists
        if (empty($content)) {
            return "# " . $version->getValue() . "\n\n" . $this->autogeneratedDelimeter;
        }

        // Given an existing file, attempt to regenerate autogenerated component
        $this->log($output, "Merging changes with existing changelog");
        $position = stripos($content, $this->autogeneratedDelimeter);
        if ($position === false) {
            $this->log(
                $output,
                "Warning: autogeneration delimiter could not be found. Content will be appended instead",
                "error"
            );
        } else {
            $content = substr($content, 0, $position);
        }
        return $content . $this->autogeneratedDelimeter;
    }

    public function getStepName()
    {
        return 'changelog';
    }

    /**
     * Commit changes to git
     *
     * @param OutputInterface $output
     * @param Library $library
     * @param Version $version
     * @param string $path
     */
    public function commitChanges(OutputInterface $output, Library $library, Version $version, $path)
    {
        $repo = $library->getRepository();
        $versionName = $version->getValue();
        $repo->run("add", array($path));
        $status = $repo->run("status");
        if (stripos($status, 'Changes to be committed:')) {
            $repo->run("commit", array("-m", "Added {$versionName} changelog"));
        }
    }
}
