#!/bin/bash

# Run XDebug session for phpunit tests

# Portable versions of the path functions (should work on Linux, MacOS and Windows)
function _dirname() { python -c 'import sys; from os.path import realpath, dirname; print(dirname(realpath(sys.argv[-1])))' $@ ; }
function _realpath() { python -c 'import sys; from os.path import realpath; print(realpath(sys.argv[-1]))' $@ ; }

SKIP_RUN_EXEC="1"
. "$(_dirname $(_realpath -f "$0"))/run"

run_docker_compose cow_debug_test $@