#!/bin/bash

# Portable versions of the path functions (should work on Linux, MacOS and Windows)
function _dirname() { python -c 'import sys; from os.path import realpath, dirname; print(dirname(realpath(sys.argv[-1])))' $@ ; }
function _realpath() { python -c 'import sys; from os.path import realpath; print(realpath(sys.argv[-1]))' $@ ; }

TGT_DIR=$(_realpath -f $(pwd))  # the target folder where we run cow from

export USER_ID=$(id -u)

CUR_FILE=$(_realpath "$0")
CUR_DIR=$(_dirname $CUR_FILE)
COW_DIR=$(_dirname $CUR_DIR)

export GIT_CONFIG=$(git config --show-origin --global -l | head -n 1 | awk '{ print substr($1, index($1, ":")+1); }')

if grep -q 'XDEBUG_HOST=localhost' "$CUR_DIR/.env" ; then
    if [ "$(uname)" = "Darwin" ] ; then
        ## Docker for Mac is run within a VM, so container localhost will be the VM
        ## the host machine can be referenced by a special DNS - host.docker.internal
        ## see https://docs.docker.com/docker-for-mac/networking/
        export XDEBUG_HOST='host.docker.internal'
    fi
fi

run_docker_compose()
{
    cd $CUR_DIR && \
    docker-compose run --rm \
        -e UID=$USER_ID \
        -e COW_DIR="$COW_DIR" \
        -e GIT_CONFIG="$GIT_CONFIG" \
        -u $USER_ID \
        -v "$COW_DIR:$COW_DIR" \
        -v "$TGT_DIR:$TGT_DIR" \
        -v "$CUR_DIR:$CUR_DIR" \
        -w "$TGT_DIR" \
        $1 ${@:2}
}

if [ ! -z "$SKIP_RUN_EXEC" ] ; then
    return;
fi

run_docker_compose cow_dev $@
