name: Keepalive

on:
  workflow_dispatch:
  # The 3rd of every month at 1:50pm UTC
  schedule:
    - cron: '50 13 3 * *'

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
